name: Deploy

on: 
  push:
    branches:
      - master

jobs:
  setupGoogleCloud:
    name: Setup Google Cloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
          version: '270.0.0'
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
    - run: gcloud info
    - run: gcloud compute ssh aw@ft-2 --zone=europe-west2-c --command="~/deploy"
