name: Deploy

on: 
  push:
    branches:
      - master

jobs:
  setupGoogleCloud:
    name: Setup Google Cloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Google Cloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
    - name: GCP Deploy
      uses: actions/gcloud/cli@master
      env:
        CLOUDSDK_CORE_PROJECT:  ${{ secrets.GOOGLE_PROJECT_ID }}
      with:
        args: compute ssh aw@ft-2 --zone=europe-west2-c --command="~/deploy"
